-- Tabelle für Cocktails erstellen
CREATE TABLE Cocktails (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    In1 INTEGER DEFAULT 0,
    In2 INTEGER DEFAULT 0,
    In3 INTEGER DEFAULT 0,
    In4 INTEGER DEFAULT 0,
    In5 INTEGER DEFAULT 0,
    In6 INTEGER DEFAULT 0,
    In7 INTEGER DEFAULT 0,
    In8 INTEGER DEFAULT 0,
    In9 INTEGER DEFAULT 0,
    In10 INTEGER DEFAULT 0,
    In11 INTEGER DEFAULT 0,
    In12 INTEGER DEFAULT 0
);